# Generated by Django 5.1.6 on 2025-10-16 10:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='ایمیل فقط می\u200cتواند شامل حروف انگلیسی، اعداد و علامت\u200cهای @ # $ & _ - ! باشد.', regex='^[A-Za-z0-9@#$&_\\-!]+$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='نام کاربری فقط می\u200cتواند شامل حروف انگلیسی، اعداد و علامت\u200cهای @ # $ & _ - ! باشد.', regex='^[A-Za-z0-9@#$&_\\-!]+$')]),
        ),
    ]
