# Generated by Django 5.1.6 on 2026-06-09 20:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_ticket_admin_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Email can only contain English letters, numbers, and the following symbols: @ # $ & _ - !', regex='^[A-Za-z0-9@#$&_\\-\\.!]+$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Username can only contain English letters, numbers, and the following symbols: @ # $ & _ - !', regex='^[A-Za-z0-9@#$&_\\-\\.!]+$')]),
        ),
    ]
