services:
  backend:
    build:
      context: .
    container_name: tisa_backend
    # command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 4
    command: sh /code/entrypoint.sh
    volumes:
      - .:/code  
      - tisa_static:/code/staticfiles
      - ./media:/var/www/media
      - protected_videos:/var/www/tisa/protected
    env_file:
      - .env
    environment:
      - DJANGO_SECRET_KEY=${DOCKER_COMPOSE_DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DOCKER_COMPOSE_DJANGO_DEBUG}
      - DJANGO_ZARINPAL_MERCHANT_ID=${DOCKER_COMPOSE_DJANGO_ZARINPAL_MERCHANT_ID}
      - DJANGO_POSTGRES_USER=${DOCKER_COMPOSE_DJANGO_POSTGRES_USER}
      - DJANGO_POSTGRES_DB=${DOCKER_COMPOSE_DJANGO_POSTGRES_DB}
      - DJANGO_POSTGRES_PASSWORD=${DOCKER_COMPOSE_DJANGO_POSTGRES_PASSWORD}
      - DJANGO_POSTGRES_HOST=${DOCKER_COMPOSE_DJANGO_POSTGRES_HOST}
      - DJANGO_EMAIL_HOST_USER=${DOCKER_COMPOSE_DJANGO_EMAIL_HOST_USER}
      - DJANGO_EMAIL_HOST_PASSWORD=${DOCKER_COMPOSE_DJANGO_EMAIL_HOST_PASSWORD}
      - DJANGO_ALLOWED_HOSTS=${DOCKER_COMPOSE_DJANGO_ALLOWED_HOSTS}
      - DJANGO_CSRF_TRUSTED_ORIGINS=${DOCKER_COMPOSE_DJANGO_CSRF_TRUSTED_ORIGINS}
    depends_on:
      - db
    # expose:
    #   - 8000
    networks:
      tisa_network:

  db:
    image: postgres:16
    container_name: tisa-db
    restart: always
    environment:
      POSTGRES_USER: ${DOCKER_COMPOSE_DJANGO_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DOCKER_COMPOSE_DJANGO_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DOCKER_COMPOSE_DJANGO_POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      tisa_network:
        aliases:
          - tisa-db-host

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx_tisa
  #   restart: always
  #   # ports:ثط
  #   #   - "80:80"
  #   #   - "443:443"
  #   volumes:
  #     - ./nginx:/etc/nginx/conf.d
  #     - static:/code/staticfiles:ro
  #     - ./media:/var/www/media:ro
  #     - protected_videos:/var/protected_videos:ro

  #     # - certbot_www:/var/www/certbot
  #     - ./certbot-webroot:/var/www/certbot
  #     - certbot_certs:/etc/letsencrypt
  #   depends_on:
  #     - backend
  #   networks:
  #     - tisa_network


  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - ./certbot-webroot:/var/www/certbot
  #     # - certbot_www:/var/www/certbot
  #     - certbot_certs:/etc/letsencrypt
  #   networks:
  #     - tisa_network

volumes:
  postgres_data:
  tisa_static:
    external: true
    name: tisa_static
  protected_videos:
    external: true
    name: protected_videos

  # certbot_www:
  # certbot_certs:

networks:
  tisa_network:
    external: true
    name: shared_net
