services:
  web:
    build:
      context: .
    container_name: django-app
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static:/usr/src/app/static
      - media:/usr/src/app/media
    env_file:
      - .env
    environment:
      - DJANGO_SECRET_KEY=${DOCKER_COMPOSE_DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DOCKER_COMPOSE_DJANGO_DEBUG}
      - DJANGO_POSTGRES_USER=${DOCKER_COMPOSE_DJANGO_POSTGRES_USER}
      - DJANGO_POSTGRES_NAME=${DOCKER_COMPOSE_DJANGO_POSTGRES_NAME}
      - DJANGO_POSTGRES_PASSWORD=${DOCKER_COMPOSE_DJANGO_POSTGRES_PASSWORD}
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${DOCKER_COMPOSE_DJANGO_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DOCKER_COMPOSE_DJANGO_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DOCKER_COMPOSE_DJANGO_POSTGRES_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      # for HTTPS later, also: - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static:/var/www/static
      - media:/var/www/media
    depends_on:
      - web

volumes:
  postgres_data:
  static:
  media: