# Generated by Django 5.1.6 on 2025-10-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_email_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='accounts/profile_image/', verbose_name='Profile Image'),
        ),
    ]
