# Generated by Django 5.1.6 on 2025-11-14 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('technical', 'مشکل فنی – خطا در سایت، دانلود نشدن ویدیو...'), ('course', 'پرسش درباره\u200cی دوره\u200cها'), ('education', 'درخواست پشتیبانی آموزشی'), ('payment', 'مشکل پرداخت/مالی'), ('feedback', 'پیشنهاد یا انتقاد'), ('other', 'سایر موارد')], max_length=50)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('o', 'Open'), ('p', 'In Progress'), ('c', 'Closed')], default='o', max_length=1)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
