# Generated by Django 5.1.6 on 2025-08-10 11:51

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(model_name="post",name="slug",field=models.SlugField(default=" "),preserve_default=False),
        migrations.AlterField(model_name="post",name="text",field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Post description")),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.ForeignKey(default="",on_delete=django.db.models.deletion.PROTECT,related_name="posts",to="blog.category"),preserve_default=False),
    ]
