# Generated by Django 5.1.6 on 2025-11-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_free_resource',
            field=models.BooleanField(default=True),
        ),
    ]
