# Generated by Django 5.1.6 on 2025-10-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_zarinpal_data_order_zarinpal_ref_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=700, verbose_name='آدرس کامل'),
        ),
    ]
