# Generated by Django 5.1.6 on 2026-06-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='admin_reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
