# Generated by Django 5.1.6 on 2025-10-28 15:03

import django.core.files.storage
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_video_videofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/var/protected_videos'), upload_to=products.models.video_upload_path),
        ),
    ]
